### ISSUE TITLE
springboot + mybatis-native unittest failed

### ISSUE THREAD

**Issue by cqsuper** [mybatis/spring-native#66]
when run app is ok, but when run unittest will failed:
Caused by: java.io.FileNotFoundException: class path resource [file:/Users/xx/.../target/classes/mybatis/mapper/userMapper.xml] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:199)
	at org.mybatis.spring.SqlSessionFactoryBean.buildSqlSessionFactory(SqlSessionFactoryBean.java:609)
	... 164 more

In class MyBatisSpringNativeAutoConfiguration
 `        resources = holders.stream()
            .flatMap(holder -> holder.getMapperLocations().stream().map(ClassPathResource::new)).toArray(
                Resource[]::new);
`
because mapperLocations is full file path, the resource can be FileSystemResource can not be ClassPathResource!
Maybe can change code like this:
`
      Resource[] resources = null;
      if (AotModeDetector.isAotModeEnabled()) {
        resources = holders.stream()
            .flatMap(holder -> holder.getMapperLocations().stream().map(ClassPathResource::new)).toArray(
                Resource[]::new);
      } else {
        resources = holders.stream()
            .flatMap(holder -> Arrays.stream(holder.getMapperLocationPatterns())
                .flatMap(location -> Stream.of(getResources(location)))).toArray(Resource[]::new);
      }
`
MyBatisScannedResourcesHolder add field mapperLocationPatterns;

**Comment by hazendaz** [comment]
@cqsuper Can you raise PR for this?
